### ISSUE TITLE
Example for signature generation 

### ISSUE THREAD

**Issue by khalaniaiyaj** [ing-bank/threshold-signatures#29]
Can you please provide an example of signature generation?

**Comment by RustMania** [comment]
Hi, it is very good idea. I should make some time this week for adding a signing application to the examples. Meanwhile, do you need a help with understanding the signing API? Let me now.

**Comment by KaiserKarel** [comment]
@RustMania I'd love some examples of correct usage as well. As you are very knowledgeable of the lib, a comparison of this versus other libs would be very nice to have in the README as well.

**Comment by faneelaIjaz** [comment]
Could you please provide the simulating examples of keysigning and verification as well

**Comment by igmar** [comment]
ING has no intention of resolving this, nor on maintaining this further, and hence, this repo will be archived. Its usage is no longer recommended, see the updated README.
