### ISSUE TITLE
Allow examining `ErrorState`

### ISSUE THREAD

**Issue by survived** [ing-bank/threshold-signatures#33]
`ErrorState` is essentially a set of occurred errors (e.g. `Vec<KeygenError>`) which should be examined in case of unsuccessful protocol termination: it contains information like which of parties behave maliciously, on which stage, etc. However, none of `ErrorState`s provide access to list of errors. 

My suggestion is to make [`errors` field] public, or add an accessor like `fn errors(&self) -> &[KeygenError]`. Unless there was an intention to hide this information.

[`errors` field]: https://github.com/ing-bank/threshold-signatures/blob/f916016aa6299bff13e90a0ecba3de3dde77186f/src/ecdsa/keygen.rs#L1055

**Comment by igmar** [comment]
ING has no intention of resolving this, nor on maintaining this further, and hence, this repo will be archived. Its usage is no longer recommended, see the updated README.
