### ISSUE TITLE
Update curv library

### ISSUE THREAD

**Issue by tmpfs** [ing-bank/threshold-signatures#35]
Hi @RustMania,

I would like to try to upgrade the dependencies so we can support the `wasm32` target (see #31); I have already done this for `multi-party-ecdsa` with support from their developers (see [this PR](https://github.com/ZenGo-X/multi-party-ecdsa/pull/144)) so I have a good idea of the changes needed to achieve this.

Are you interested in updating `curv-kzen` and working with me to achieve this?

Thanks 🙏

**Comment by RustMania** [comment]
Hi, 
I m glad that you contact me on this matter. I have started this migration 6 m ago, and I met few problems which needed to be addressed in curv, so I stopped.
 Yes, I m interested in working with you. Shall we find out which communication platform suits better?

**Comment by tmpfs** [comment]
Oh, so you think there is no clear upgrade path for `curv`? Do you recall what the problem(s) were?

Happy to talk about this further as I think it would be good if we can upgrade this dependency, you can reach me by email `muji [at] tmpfs [dot] org` and then we can switch to another platform if you prefer. Thanks 🙏

**Comment by heatherowls** [comment]
Hi,
i met the same problem, the curv-kzen needs to be updated to support wasm, how is it now?

**Comment by igmar** [comment]
ING has no intention of resolving this, nor on maintaining this further, and hence, this repo will be archived. Its usage is no longer recommended, see the updated README.
