### ISSUE TITLE
Warning building threshold-signature project

### ISSUE THREAD

**Issue by yrvent** [ing-bank/threshold-signatures#36]
Hi!

I'm interested to understand about thrreshold-signature.
I clone the threshold-signature project and I get the below message trying to build the project.
Could you help me? 

warning: field is never read: `errors`
    --> src\ecdsa\keygen.rs:1055:5
     |
1055 |     errors: Vec<KeygenError>,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: `#[warn(dead_code)]` on by default

warning: field is never read: `old_params`
   --> src\ecdsa\resharing.rs:444:9
    |
444 |         old_params: Parameters,
    |         ^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `errors`
   --> src\ecdsa\signature.rs:428:5
    |
428 |     errors: Vec<SigningError>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: `ecdsa-mpc` (lib) generated 3 warnings

Thanks,

**Comment by igmar** [comment]
ING has no intention of resolving this, nor on maintaining this further, and hence, this repo will be archived. Its usage is no longer recommended, see the updated README.
