### ISSUE TITLE
Can not build due to missing libgmp on macOS Monterey 12.5.1

### ISSUE THREAD

**Issue by chiro-hiro** [ing-bank/threshold-signatures#37]
## Build error 

```
error: linking with `cc` failed: exit status: 1
[....]
  = note: ld: library not found for -lgmp
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `ecdsa-mpc` due to previous error
```

## How to fix?

Install GMP with homebrew:

```
brew install gmp
```

Make sure gmp linked:

```
brew link --force gmp
```

Create file `.cargo/config` in source code folder:

```
[target.x86_64-apple-darwin]
rustflags = [
  "-L", "/opt/homebrew/lib",
  "-L", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib",
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-L", "/opt/homebrew/lib",
  "-L", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib",
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```

These flags was used to guide `rustc` to look up libraries from homebrew. I'm prefer an official patch.

**Comment by ghost** [comment]
seems we share the same interest 🤭

**Comment by RustMania** [comment]
I recall that when I had this problem on new Mac Apple Silicon , I installed the lib:
>brew install gmp
I have checked what had been installed:
>brew list gmp

/opt/homebrew/Cellar/gmp/6.2.1_1/include/ (2 files)
/opt/homebrew/Cellar/gmp/6.2.1_1/lib/libgmp.10.dylib
/opt/homebrew/Cellar/gmp/6.2.1_1/lib/libgmpxx.4.dylib
/opt/homebrew/Cellar/gmp/6.2.1_1/lib/pkgconfig/ (2 files)
/opt/homebrew/Cellar/gmp/6.2.1_1/lib/ (4 other files)
/opt/homebrew/Cellar/gmp/6.2.1_1/share/info/ (3 files)

and then I found that required library files already have symlinks in /opt/homebrew/lib, so that adding

export LIBRARY_PATH=/opt/homebrew/lib

to .profile ( or .zprofile ) solved the issue

**Comment by chiro-hiro** [comment]
> I recall that when I had this problem on new Mac Apple Silicon , I installed the lib:
> 
> > brew install gmp
> > I have checked what had been installed:
> > brew list gmp
> 
> /opt/homebrew/Cellar/gmp/6.2.1_1/include/ (2 files) /opt/homebrew/Cellar/gmp/6.2.1_1/lib/libgmp.10.dylib /opt/homebrew/Cellar/gmp/6.2.1_1/lib/libgmpxx.4.dylib /opt/homebrew/Cellar/gmp/6.2.1_1/lib/pkgconfig/ (2 files) /opt/homebrew/Cellar/gmp/6.2.1_1/lib/ (4 other files) /opt/homebrew/Cellar/gmp/6.2.1_1/share/info/ (3 files)
> 
> and then I found that required library files already have symlinks in /opt/homebrew/lib, so that adding
> 
> export LIBRARY_PATH=/opt/homebrew/lib
> 
> to .profile ( or .zprofile ) solved the issue

Adding a `.cargo/config` could solve this problem for everyone. We just needed to figure out what is the different between arch and OS version?.

**Comment by ataki** [comment]
On a Mac Apple Silicon (Monterey 12.0), after populating the `.cargo/config` AND setting `LIBRARY_PATH`, I get the following issue:

```
warning: `ecdsa-mpc` (lib) generated 3 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/examples/keygen 2 5 test_keys --use-range-proofs`
dyld[94085]: missing symbol called
[1]    94085 abort      cargo run --example keygen 2 5 test_keys --use-range-proofs
```

Any pointers for what's happening? I'm new to the Rust build process.

**Comment by igmar** [comment]
ING has no intention of resolving this, nor on maintaining this further, and hence, this repo will be archived. Its usage is no longer recommended, see the updated README.
