### ISSUE TITLE
Biblio link [5] is incorrect

### ISSUE THREAD

**Issue by SorinS** [ing-bank/threshold-signatures#38]
The correct URL is:
https://www.ingwb.com/binaries/content/assets/insights/themes/distributed-ledger-technology/ing-releases-multiparty-threshold-signing-library-to-improve-customer-security/threshold-signatures-using-secure-multiparty-computation.pdf

**Comment by igmar** [comment]
ING has no intention of resolving this, nor on maintaining this further, and hence, this repo will be archived. Its usage is no longer recommended, see the updated README.
