### ISSUE TITLE
Q: How to persist protocol state between rounds?

### ISSUE THREAD

**Issue by naughtyfox** [ing-bank/threshold-signatures#39]
Hi!

Because of the extremely asynchronous nature of clients' applications, it may take up to weeks when all clients appear online to revolve another key exchange round. How to persist intermediate data between rounds and restore it? For example, if two clients agreed to make a signature using their iphones and in the middle of the process one of them goes offline for a couple of days. It's not possible to keep the app online all the time. 

Is it possible to save unfinished signature protocol and restore it later? How do you address this problem?

Thank you.

**Comment by igmar** [comment]
ING has no intention of resolving this, nor on maintaining this further, and hence, this repo will be archived. Its usage is no longer recommended, see the updated README.
