### ISSUE TITLE
Tsshock

### ISSUE THREAD

**Issue by ferdinandvroom** [ing-bank/threshold-signatures#41]
According to Steve Gibson, Security Now podcast, ING Bank uses a vulnerable threshold ECDSA software implementation...
https://github.com/verichains/tsshock

Haven't looked into it, but does it concern this project?

**Comment by igmar** [comment]
Yes, it does. See the updated README. ING has no intention of resolving this, nor on maintaining this further, and hence, this repo will be archived.
