### ISSUE TITLE
dlog_proof() is not secure 

### ISSUE THREAD

**Issue by omershlo** [ing-bank/threshold-signatures#9]
referring to https://github.com/ing-bank/threshold-signatures/blob/master/src/algorithms/zkp.rs#L352 
let us look at the following computation: `let r: BigInt = &v - (dlog * &challenge);`  

This computation is done in this case over the integers (as it should), 
the size of `v` must be picked to hide `dlog * &challenge` 
however in the code: 
|v| <  N_tilde ( ~< 2^2048 bits )
|challenge| < 2^256 
|dlog| ~< N_tilde ( ~< 2^2048 bits )

therefore |v| << |challenge * dlog| 
which means that `r` value sent to the verifier leaks bits (for example, verifier can divide `r` by the  challenge and learn many of the leading bits of `dlog`)

**Comment by RustMania** [comment]
Omer wrote:

> This is still not secure... you cannot do mod q on r : for example now the verifier of the dlog proof will get information on the order of N_tilde which should be kept a secret. As I pointed out in #9 r should be over the integers.

> In general I suggest to follow an existing dlog_proof for composite modulus from the literature.btw, you can work with much smaller h1,h2 and make the entire computation more efficient

The PR+branch removed.
